version: '1.0.0'
services:
  server:
    build:
      context: ./src
    command: >
      sh -c "python manage.py migrate
      && daphne main.asgi:application -b 0.0.0.0 -p 8000"
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    env_file:
      - .env_file/dev.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=agrohub
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  ai:
    build:
      context: ./ai
    restart: unless-stopped
    ports:
      - 8001:8001
    volumes:
      - ./ai:/app
volumes:
  db-data:
secrets:
  db-password:
    file: .secrets/db/password.txt

