# Generated by Django 5.0.3 on 2024-03-09 16:47

import utilities.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmphoto',
            name='photo',
            field=models.ImageField(upload_to=utilities.helpers.farm_photos_path),
        ),
    ]
