# Generated by Django 5.0.3 on 2024-03-10 07:25

import utilities.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_farmphoto_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='photo',
            field=models.ImageField(upload_to=utilities.helpers.farm_crop_photos_path),
        ),
    ]
