# Generated by Django 5.0.3 on 2024-03-13 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer'),
        ),
        migrations.AddField(
            model_name='farmlocation',
            name='farm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmers.farm'),
        ),
        migrations.AddField(
            model_name='farmphoto',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farm'),
        ),
    ]
